/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import transfer.KlijentskiTransferObjekat;
import transfer.ServerskiTransferObjekat;

/**
 *
 * @author Milica
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {

    Korisnik ulogovani;
    
    

    public void setUlogovani(Korisnik ulogovani) {
        this.ulogovani = ulogovani;
    }

    public Korisnik getUlogovani() {
        return ulogovani;
    }

    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma() {
        initComponents();
        setSize(1500,1200);
        centar();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmKlijent = new javax.swing.JMenu();
        jmiUnosKlijenta = new javax.swing.JMenuItem();
        jmiPrikazKlijenta = new javax.swing.JMenuItem();
        jmKurs = new javax.swing.JMenu();
        jmiUnosKursa = new javax.swing.JMenuItem();
        jmiPrikazKursa = new javax.swing.JMenuItem();
        jmPrijava = new javax.swing.JMenu();
        jmiUnosPrijave = new javax.swing.JMenuItem();
        jmiPrikazPrijave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klijent");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jmKlijent.setText("Klijent");
        jmKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKlijentActionPerformed(evt);
            }
        });

        jmiUnosKlijenta.setText("Unos klijenta");
        jmiUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKlijentaActionPerformed(evt);
            }
        });
        jmKlijent.add(jmiUnosKlijenta);

        jmiPrikazKlijenta.setText("Prikaz klijenta");
        jmiPrikazKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazKlijentaActionPerformed(evt);
            }
        });
        jmKlijent.add(jmiPrikazKlijenta);

        jMenuBar1.add(jmKlijent);

        jmKurs.setText("Kurs");

        jmiUnosKursa.setText("Unos kursa");
        jmiUnosKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKursaActionPerformed(evt);
            }
        });
        jmKurs.add(jmiUnosKursa);

        jmiPrikazKursa.setText("Prikaz kursa");
        jmiPrikazKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazKursaActionPerformed(evt);
            }
        });
        jmKurs.add(jmiPrikazKursa);

        jMenuBar1.add(jmKurs);

        jmPrijava.setText("Prijava");

        jmiUnosPrijave.setText("Unos prijave");
        jmiUnosPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPrijaveActionPerformed(evt);
            }
        });
        jmPrijava.add(jmiUnosPrijave);

        jmiPrikazPrijave.setText("Prikaz prijave");
        jmiPrikazPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazPrijaveActionPerformed(evt);
            }
        });
        jmPrijava.add(jmiPrikazPrijave);

        jMenuBar1.add(jmPrijava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKlijentActionPerformed
    
    }//GEN-LAST:event_jmKlijentActionPerformed

    private void jmiUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKlijentaActionPerformed
        
        UnosKlijenta uk = new UnosKlijenta();
        uk.setVisible(true);
    }//GEN-LAST:event_jmiUnosKlijentaActionPerformed

    private void jmiPrikazKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazKlijentaActionPerformed
        PrikazKlijenata pk = new PrikazKlijenata();
        pk.setVisible(true);
    }//GEN-LAST:event_jmiPrikazKlijentaActionPerformed

    private void jmiUnosKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKursaActionPerformed
        UnosKursa u = new UnosKursa();
        u.setVisible(true);
    }//GEN-LAST:event_jmiUnosKursaActionPerformed

    private void jmiPrikazKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazKursaActionPerformed
        
        PrikazKurseva p = new PrikazKurseva();
        p.setVisible(true);
    }//GEN-LAST:event_jmiPrikazKursaActionPerformed

    private void jmiUnosPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPrijaveActionPerformed
        
        UnosPrijave u = new UnosPrijave();
        u.setUlogovani(ulogovani);
        u.setVisible(true);
    }//GEN-LAST:event_jmiUnosPrijaveActionPerformed

    private void jmiPrikazPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazPrijaveActionPerformed
        PrikazPrijave pp = new PrikazPrijave();
        pp.setVisible(true);
    }//GEN-LAST:event_jmiPrikazPrijaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        KlijentskiTransferObjekat kto = new KlijentskiTransferObjekat();
        kto.setParametar(ulogovani);
        kto.setOperacija(konstante.Konstante.IZLOGUJ_KORISNIKA);
        komunikacija.Komunikacija.getInstanca().posaljiZahtev(kto);
        ServerskiTransferObjekat sto = komunikacija.Komunikacija.getInstanca().primiOdgovor();

        JOptionPane.showMessageDialog(this, sto.getPoruka());
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmKlijent;
    private javax.swing.JMenu jmKurs;
    private javax.swing.JMenu jmPrijava;
    private javax.swing.JMenuItem jmiPrikazKlijenta;
    private javax.swing.JMenuItem jmiPrikazKursa;
    private javax.swing.JMenuItem jmiPrikazPrijave;
    private javax.swing.JMenuItem jmiUnosKlijenta;
    private javax.swing.JMenuItem jmiUnosKursa;
    private javax.swing.JMenuItem jmiUnosPrijave;
    // End of variables declaration//GEN-END:variables

    private void centar() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2- this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
}
