/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kurs;
import domen.Nivo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import transfer.KlijentskiTransferObjekat;
import transfer.ServerskiTransferObjekat;

/**
 *
 * @author Milica
 */
public class UnosKursa extends javax.swing.JFrame {

    Kurs k;
    PrikazKurseva pk;

    /**
     * Creates new form UnosKursa
     */
    public UnosKursa() {
        initComponents();
        podesi();
        btnIzmeni.setVisible(false);
        popunikombo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        txtBrojCasova = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatumPo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDatumZa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaxBrKl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbNivo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos kursa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nivo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cena:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Broj casova:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Datum pocetka:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Datum zavrsetka:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Maksimalan broj klijenata:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Naziv:");

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(0, 102, 102));
        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(0, 102, 102));
        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel6.setText("format: dd.MM.yyyy");

        jLabel9.setText("format: dd.MM.yyyy");

        cmbNivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbNivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(txtMaxBrKl, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumZa, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumPo, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNivo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbNivo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumPo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumZa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaxBrKl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        String naziv = txtNaziv.getText();
        
        String c = txtCena.getText();
        String brCas = txtBrojCasova.getText();
        String datP = txtDatumPo.getText();
        String datZ = txtDatumZa.getText();
        String maks = txtMaxBrKl.getText();

        if (naziv.isEmpty() ||  c.isEmpty() || brCas.isEmpty() || datP.isEmpty() || datZ.isEmpty() || maks.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite sva polja.");
            return;
        }
        
        Nivo nivo = (Nivo) cmbNivo.getSelectedItem();

        double cena = 0;
        try {
            cena = Double.parseDouble(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "cena mora da bude double.");
            return;
        }
        int brojCasova = 0;
        try {
            brojCasova = Integer.parseInt(brCas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Broj casova mora da bude integer.");
            return;
        }
        
         int maksBrKlijenata = 0;
        try {
            maksBrKlijenata = Integer.parseInt(maks);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Maksnimalan broj klijenata mora da bude integer.");
            return;
        }

        
        if (datP.length()!= 10) {
            JOptionPane.showMessageDialog(this, "Unesite datum pocetka u navedenom formatu.");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumPocetka = null;
        try {
            datumPocetka = sdf.parse(datP);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite datum pocetka u navedenom formatu.");
            return;
            //Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datZ.length()!= 10) {
            JOptionPane.showMessageDialog(this, "Unesite datum zavrsetka u navedenom formatu.");
            return;
        }
        
        Date daumZavrsetka=null;
        try {
            daumZavrsetka = sdf.parse(datZ);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite datum zavrsetka u navedenom formatu.");
            return;
            //Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Kurs k = new Kurs(-1, naziv, nivo, cena, brojCasova, datumPocetka, daumZavrsetka, maksBrKlijenata);
        KlijentskiTransferObjekat kto = new KlijentskiTransferObjekat();
        kto.setParametar(k);
        kto.setOperacija(konstante.Konstante.SACUVAJ_KURS);
        komunikacija.Komunikacija.getInstanca().posaljiZahtev(kto);
        ServerskiTransferObjekat sto = komunikacija.Komunikacija.getInstanca().primiOdgovor();

        JOptionPane.showMessageDialog(this, sto.getPoruka());


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
          String naziv = txtNaziv.getText();
        
        String c = txtCena.getText();
        String brCas = txtBrojCasova.getText();
        String datP = txtDatumPo.getText();
        String datZ = txtDatumZa.getText();
        String maks = txtMaxBrKl.getText();

        if (naziv.isEmpty() ||  c.isEmpty() || brCas.isEmpty() || datP.isEmpty() || datZ.isEmpty() || maks.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite sva polja.");
            return;
        }
        
        Nivo nivo = (Nivo) cmbNivo.getSelectedItem();

        double cena = 0;
        try {
            cena = Double.parseDouble(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "cena mora da bude double.");
            return;
        }
        int brojCasova = 0;
        try {
            brojCasova = Integer.parseInt(brCas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Broj casova mora da bude integer.");
            return;
        }
        
         int maksBrKlijenata = 0;
        try {
            maksBrKlijenata = Integer.parseInt(maks);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Maksnimalan broj klijenata mora da bude integer.");
            return;
        }

        
        if (datP.length()!= 10) {
            JOptionPane.showMessageDialog(this, "Unesite datum pocetka u navedenom formatu.");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumPocetka = null;
        try {
            datumPocetka = sdf.parse(datP);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite datum pocetka u navedenom formatu.");
            return;
            //Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datZ.length()!= 10) {
            JOptionPane.showMessageDialog(this, "Unesite datum zavrsetka u navedenom formatu.");
            return;
        }
        
        Date daumZavrsetka=null;
        try {
            daumZavrsetka = sdf.parse(datZ);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite datum zavrsetka u navedenom formatu.");
            return;
            //Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Kurs kurs = new Kurs(k.getKursID(), naziv, nivo, cena, brojCasova, datumPocetka, daumZavrsetka, maksBrKlijenata);
        KlijentskiTransferObjekat kto = new KlijentskiTransferObjekat();
        kto.setParametar(kurs);
        kto.setOperacija(konstante.Konstante.IZMENI_KURS);
        komunikacija.Komunikacija.getInstanca().posaljiZahtev(kto);
        ServerskiTransferObjekat sto = komunikacija.Komunikacija.getInstanca().primiOdgovor();
        JOptionPane.showMessageDialog(this, sto.getPoruka());
        pk.srediTabelu();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosKursa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbNivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBrojCasova;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDatumPo;
    private javax.swing.JTextField txtDatumZa;
    private javax.swing.JTextField txtMaxBrKl;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void podesi() {
        setSize(1100, 800);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    private void popunikombo() {
        cmbNivo.removeAllItems();
        cmbNivo.addItem(Nivo.A1);
        cmbNivo.addItem(Nivo.B1);
        cmbNivo.addItem(Nivo.C1);
        cmbNivo.addItem(Nivo.A2);
        cmbNivo.addItem(Nivo.B2);
        cmbNivo.addItem(Nivo.C2);
    }
    
    void izmeniFormu(Kurs k, PrikazKurseva pk) {
        btnIzmeni.setVisible(true);
        
        btnSacuvaj.setVisible(false);
        this.k = k;
        this.pk = pk;
        txtNaziv.setText(k.getNaziv());
        cmbNivo.setSelectedItem(k.getNivo());
        txtCena.setText(k.getCena()+"");
        txtBrojCasova.setText(k.getBrojCasova()+"");
        txtMaxBrKl.setText(k.getMaksimalanBrKlijenata()+"");
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        String dat = sdf.format(k.getDatumPocetka());
        txtDatumPo.setText(dat);
        String dat2= sdf.format(k.getDatumZavrsetka());
        txtDatumZa.setText(dat2);

    }
}
